### ISSUE TITLE
#valid not returning same response as valid_for_country?

### ISSUE THREAD

**Issue by desheikh** [ianks/mini_phone#7]
Hello!
For a Canadian Alberta number: 8255649738

```
MiniPhone.valid_for_country?('8255649738', 'CA') => true
```

```
MiniPhone.parse('8255649738', 'CA').valid? => false
MiniPhone.parse('8255649738', 'CA').region_code => 'US'
```

Based on https://libphonenumber.appspot.com/phonenumberparser?number=8255649738&country=CA the response should be `true` and `CA`.

**Comment by ianks** [comment]
Thanks for the report, looking into this now.

**Comment by ianks** [comment]
Should be fixed now :smile:
