### ISSUE TITLE
heroku installation/usage

### ISSUE THREAD

**Issue by gagalago** [ianks/mini_phone#8]
I tried to use this gem on an application hosted on heroku but as this gem depend one libphonenumber, I was not able to build the application on heroku. Do you know how I can be able to do it?

**Comment by ianks** [comment]
i'm not familiar with heroku specifically, but you would need to install the `libphonenumber-dev` debian package. [there is some info here on how to accomplish that](https://help.heroku.com/IYRYW6VB/how-do-i-install-additional-software-packages-that-my-application-requires).

let me know if you are able to do it!

**Comment by espen** [comment]
Here how to do it:

Add the apt buildpack to your app:
`heroku buildpacks:add --index 1 heroku-community/apt`

Then in your repo add a Aptfile file with content:
`libphonenumber-dev`

Perphaps this should be added to the readme or wiki?

**Comment by ianks** [comment]
I would totally accept a PR for that @espen
